//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCalculadora.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Multa", Namespace="http://schemas.datacontract.org/2004/07/ServicioCalculadora2")]
    [System.SerializableAttribute()]
    public partial class Multa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosPerdidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClienteCalculadora.ServiceReference1.Multa multaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuntosPerdidos {
            get {
                return this.PuntosPerdidosField;
            }
            set {
                if ((this.PuntosPerdidosField.Equals(value) != true)) {
                    this.PuntosPerdidosField = value;
                    this.RaisePropertyChanged("PuntosPerdidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClienteCalculadora.ServiceReference1.Multa multa {
            get {
                return this.multaField;
            }
            set {
                if ((object.ReferenceEquals(this.multaField, value) != true)) {
                    this.multaField = value;
                    this.RaisePropertyChanged("multa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISCalculadora")]
    public interface ISCalculadora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/ComprobarPuntos", ReplyAction="http://tempuri.org/ISCalculadora/ComprobarPuntosResponse")]
        int ComprobarPuntos(int Dni, string Matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/ComprobarMultas", ReplyAction="http://tempuri.org/ISCalculadora/ComprobarMultasResponse")]
        ClienteCalculadora.ServiceReference1.Multa[] ComprobarMultas(int Dni, string Matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/Identificacion", ReplyAction="http://tempuri.org/ISCalculadora/IdentificacionResponse")]
        int Identificacion(string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/PonerMulta", ReplyAction="http://tempuri.org/ISCalculadora/PonerMultaResponse")]
        int PonerMulta(string Matricula, string Fecha, int Puntos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/QuitarMulta", ReplyAction="http://tempuri.org/ISCalculadora/QuitarMultaResponse")]
        int QuitarMulta(string Matricula, string Fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/AltaVehiculo", ReplyAction="http://tempuri.org/ISCalculadora/AltaVehiculoResponse")]
        int AltaVehiculo(int Dni, string Matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCalculadora/BajaVehiculo", ReplyAction="http://tempuri.org/ISCalculadora/BajaVehiculoResponse")]
        int BajaVehiculo(int Dni, string Matricula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISCalculadoraChannel : ClienteCalculadora.ServiceReference1.ISCalculadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCalculadoraClient : System.ServiceModel.ClientBase<ClienteCalculadora.ServiceReference1.ISCalculadora>, ClienteCalculadora.ServiceReference1.ISCalculadora {
        
        public SCalculadoraClient() {
        }
        
        public SCalculadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCalculadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCalculadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCalculadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ComprobarPuntos(int Dni, string Matricula) {
            return base.Channel.ComprobarPuntos(Dni, Matricula);
        }
        
        public ClienteCalculadora.ServiceReference1.Multa[] ComprobarMultas(int Dni, string Matricula) {
            return base.Channel.ComprobarMultas(Dni, Matricula);
        }
        
        public int Identificacion(string Password) {
            return base.Channel.Identificacion(Password);
        }
        
        public int PonerMulta(string Matricula, string Fecha, int Puntos) {
            return base.Channel.PonerMulta(Matricula, Fecha, Puntos);
        }
        
        public int QuitarMulta(string Matricula, string Fecha) {
            return base.Channel.QuitarMulta(Matricula, Fecha);
        }
        
        public int AltaVehiculo(int Dni, string Matricula) {
            return base.Channel.AltaVehiculo(Dni, Matricula);
        }
        
        public int BajaVehiculo(int Dni, string Matricula) {
            return base.Channel.BajaVehiculo(Dni, Matricula);
        }
    }
}
