/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaSociosActividad extends javax.swing.JFrame {

    /**
     * Creates new form VistaSociosActividad
     */
    public VistaSociosActividad() {
        initComponents();
    }
    
    //Se sobcreescribe el método isCellEditable para hacer que las filas no se puedan editar al hacer doble click
    public DefaultTableModel modeloTablaSociosActividad = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    //Función para "dibujar" la tabla SociosActividad
    public void dibujarTablaSociosActividad(VistaSociosActividad vSociosActividad)
    {
        vSociosActividad.jTableSociosActividad.setModel(modeloTablaSociosActividad);
        
        String[] columnasTabla = {"Nombre", "Correo"};
        modeloTablaSociosActividad.setColumnIdentifiers(columnasTabla);
        
        //Para no permitir el redimensionamiento de las columnas con el ratón
        vSociosActividad.jTableSociosActividad.getTableHeader().setResizingAllowed(false);
        vSociosActividad.jTableSociosActividad.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        //Fijamos el ancho de las columnas
        vSociosActividad.jTableSociosActividad.getColumnModel().getColumn(0).setPreferredWidth(150);
        vSociosActividad.jTableSociosActividad.getColumnModel().getColumn(1).setPreferredWidth(150);

    }
    
    //Función para vaciar el contenido de la tabla
    public void vaciarTablaSociosActividad()
    {
        while(modeloTablaSociosActividad.getRowCount() > 0)
        {
            modeloTablaSociosActividad.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFiltrarProcedimiento = new javax.swing.JButton();
        jButtonSalirProcedimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSociosActividad = new javax.swing.JTable();
        jComboBoxFiltrarProcedimiento = new javax.swing.JComboBox<>();

        jButtonFiltrarProcedimiento.setText("Filtrar");
        jButtonFiltrarProcedimiento.setActionCommand("FiltrarProcedimiento");

        jButtonSalirProcedimiento.setText("Salir");
        jButtonSalirProcedimiento.setActionCommand("SalirProcedimiento");
        jButtonSalirProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirProcedimientoActionPerformed(evt);
            }
        });

        jTableSociosActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSociosActividad);

        jComboBoxFiltrarProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltrarProcedimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxFiltrarProcedimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFiltrarProcedimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalirProcedimiento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jComboBoxFiltrarProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiltrarProcedimiento)
                    .addComponent(jButtonSalirProcedimiento))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirProcedimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirProcedimientoActionPerformed

    private void jComboBoxFiltrarProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltrarProcedimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltrarProcedimientoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonFiltrarProcedimiento;
    public javax.swing.JButton jButtonSalirProcedimiento;
    public javax.swing.JComboBox<String> jComboBoxFiltrarProcedimiento;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSociosActividad;
    // End of variables declaration//GEN-END:variables
}
