 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Socio;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaSocio extends javax.swing.JPanel {

    /**
     * Creates new form VistaSocio
     */
    public VistaSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Se sobreescribe el método isCellEditable para hacer que las filas no se puedan editar al hacer doble click
    public DefaultTableModel modeloTablaSocios = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    public void dibujarTablaSocios(VistaSocio vSocio)
    {
        vSocio.jTableSocios.setModel(modeloTablaSocios);
        
        String[] columnasTabla = {"Numero Socio", "Nombre", "DNI", "Fecha nacimiento", "Teléfono", "Correo", "Fecha entrada", "Categoría"};
        modeloTablaSocios.setColumnIdentifiers(columnasTabla);
        
        //Para no permitir el redimensionamiento de las columnas con el ratón
        vSocio.jTableSocios.getTableHeader().setResizingAllowed(false);
        vSocio.jTableSocios.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
        //Así se fija el ancho de las columnas
        vSocio.jTableSocios.getColumnModel().getColumn(0).setPreferredWidth(40);
        vSocio.jTableSocios.getColumnModel().getColumn(1).setPreferredWidth(200);
        vSocio.jTableSocios.getColumnModel().getColumn(2).setPreferredWidth(70);
        vSocio.jTableSocios.getColumnModel().getColumn(3).setPreferredWidth(90);
        vSocio.jTableSocios.getColumnModel().getColumn(4).setPreferredWidth(70);
        vSocio.jTableSocios.getColumnModel().getColumn(5).setPreferredWidth(230);
        vSocio.jTableSocios.getColumnModel().getColumn(6).setPreferredWidth(90);
        vSocio.jTableSocios.getColumnModel().getColumn(7).setPreferredWidth(20);

    }
    
    public void rellenarTablaSocios(ArrayList<Socio> socios) //Ejemplo de función para mostrar los datos de la tabla SOCIO a partir de una lista de socios
    {
        Object[] fila = new Object[8];
        int numRegistros = socios.size();
        
        for(int i=0; i<numRegistros; i++)
        {
            fila[0] = socios.get(i).getNumeroSocio();
            fila[1] = socios.get(i).getNombre();
            fila[2] = socios.get(i).getDni();
            fila[3] = socios.get(i).getFechaNacimiento();
            fila[4] = socios.get(i).getTelefono();
            fila[5] = socios.get(i).getCorreo();
            fila[6] = socios.get(i).getFechaEntrada();
            fila[7] = socios.get(i).getCategoria();

            modeloTablaSocios.addRow(fila);
        }
    }
    
    public void vaciarTablaSocios() //Ejemplo de función para vaciar el contenido de la tabla SOCIO
    {
        while(modeloTablaSocios.getRowCount() > 0)
        {
            modeloTablaSocios.removeRow(0);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGestionDeSocios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSocios = new javax.swing.JTable();
        jTextFieldNumeroSocio = new javax.swing.JTextField();
        jLabelNumeroSocio = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonVaciarTabla = new javax.swing.JButton();
        jButtonListarMonitores = new javax.swing.JButton();
        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelFechaEntrada = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextFieldCategoria = new javax.swing.JTextField();
        jLabelFechaNacimiento = new javax.swing.JLabel();
        jDateChooserFechaEntradaSocio = new com.toedter.calendar.JDateChooser();
        jDateChooserFechaNacimientoSocio = new com.toedter.calendar.JDateChooser();

        jLabelGestionDeSocios.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelGestionDeSocios.setForeground(new java.awt.Color(102, 102, 255));
        jLabelGestionDeSocios.setText("Gestión de Socios");

        jTableSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSocios);

        jLabelNumeroSocio.setText("Numero Socio");

        jLabelNombre.setText("Nombre");

        jLabelDNI.setText("DNI");

        jLabelTelefono.setText("Teléfono");

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.setActionCommand("InsertarSocio");

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setActionCommand("ActualizarSocio");

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setActionCommand("EliminarSocio");

        jButtonVaciarTabla.setText("Vaciar Tabla");
        jButtonVaciarTabla.setActionCommand("VaciarTablaSocio");

        jButtonListarMonitores.setText("Listar Socios");
        jButtonListarMonitores.setActionCommand("ListarSocios");

        jLabelCorreo.setText("Correo");

        jLabelFechaEntrada.setText("Fecha de Entrada");

        jLabelCategoria.setText("Categoría");

        jLabelFechaNacimiento.setText("Fecha Nacimiento");

        jDateChooserFechaEntradaSocio.setToolTipText("");
        jDateChooserFechaEntradaSocio.setDateFormatString("dd/MM/yyyy");

        jDateChooserFechaNacimientoSocio.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGestionDeSocios)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNumeroSocio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNumeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(266, 266, 266)
                                        .addComponent(jLabelCorreo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jLabelDNI)
                                            .addComponent(jLabelTelefono))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonActualizar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonEliminar)))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFechaEntrada)
                                            .addComponent(jLabelCategoria)
                                            .addComponent(jLabelFechaNacimiento))))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserFechaEntradaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserFechaNacimientoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonInsertar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVaciarTabla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListarMonitores)))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGestionDeSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroSocio)
                            .addComponent(jTextFieldNumeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCorreo)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaEntrada)))
                    .addComponent(jDateChooserFechaEntradaSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTelefono)
                        .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFechaNacimiento))
                    .addComponent(jDateChooserFechaNacimientoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertar)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVaciarTabla)
                    .addComponent(jButtonListarMonitores))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonInsertar;
    public javax.swing.JButton jButtonListarMonitores;
    public javax.swing.JButton jButtonVaciarTabla;
    public com.toedter.calendar.JDateChooser jDateChooserFechaEntradaSocio;
    public com.toedter.calendar.JDateChooser jDateChooserFechaNacimientoSocio;
    public javax.swing.JLabel jLabelCategoria;
    public javax.swing.JLabel jLabelCorreo;
    public javax.swing.JLabel jLabelDNI;
    public javax.swing.JLabel jLabelFechaEntrada;
    public javax.swing.JLabel jLabelFechaNacimiento;
    public javax.swing.JLabel jLabelGestionDeSocios;
    public javax.swing.JLabel jLabelNombre;
    public javax.swing.JLabel jLabelNumeroSocio;
    public javax.swing.JLabel jLabelTelefono;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSocios;
    public javax.swing.JTextField jTextFieldCategoria;
    public javax.swing.JTextField jTextFieldCorreo;
    public javax.swing.JTextField jTextFieldDNI;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldNumeroSocio;
    public javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
