<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
load("C:/Users/usuario/Desktop/RCars.RData")
```


```{r}
library(abind, pos=17)
```


```{r}
library(e1071, pos=18)
```


```{r}
numSummary(RCars[,c("consumo", "peso")], statistics=c("sd", "cv"), quantiles=c(0,.25,.5,.75,1,0.30))
```

```{r}
numSummary(RCars[,"peso"], groups=RCars$origen, statistics=c("skewness", "kurtosis"), quantiles=c(0,.25,.5,
  .75,1,0.30), type="1")
```

```{r}
RCars <- within(RCars, {
  cilindr_fac <- as.factor(cilindr)
})
```

```{r}
with(RCars, tapply(consumo, list(cilindr_fac, origen), mean, na.rm=TRUE))
```

```{r}
with(RCars, tapply(consumo, list(cilindr_fac, origen), median, na.rm=TRUE))
```

```{r}
with(RCars, tapply(consumo, list(cilindr_fac, origen), sd, na.rm=TRUE))
```

```{r}
RCars <- within(RCars, {
  año_fac <- as.factor(año)
})
```

```{r}
with(RCars, tapply(consumo, list(año_fac, cilindr_fac, origen), mean, na.rm=TRUE))
```

```{r}
local({
  .Table <- with(RCars, table(origen))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
```

```{r}
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nColumn percentages:\n")
  print(colPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

```{r}
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nRow percentages:\n")
  print(rowPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
```

