
load("C:/Users/usuario/Desktop/RCars.RData")
library(abind, pos=17)
library(e1071, pos=18)
numSummary(RCars[,c("consumo", "peso")], statistics=c("sd", "cv"), quantiles=c(0,.25,.5,.75,1,0.30))
numSummary(RCars[,"peso"], groups=RCars$origen, statistics=c("skewness", "kurtosis"), quantiles=c(0,.25,.5,
  .75,1,0.30), type="1")
RCars <- within(RCars, {
  cilindr_fac <- as.factor(cilindr)
})
with(RCars, tapply(consumo, list(cilindr_fac, origen), mean, na.rm=TRUE))
with(RCars, tapply(consumo, list(cilindr_fac, origen), median, na.rm=TRUE))
with(RCars, tapply(consumo, list(cilindr_fac, origen), sd, na.rm=TRUE))
RCars <- within(RCars, {
  año_fac <- as.factor(año)
})
with(RCars, tapply(consumo, list(año_fac, cilindr_fac, origen), mean, na.rm=TRUE))
local({
  .Table <- with(RCars, table(origen))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nColumn percentages:\n")
  print(colPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nRow percentages:\n")
  print(rowPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})

