package Vista;

/**
 *
 * @author adrianmorenomonterde
 */
public class VistaSociosActividad extends javax.swing.JFrame {

    /**
     * Creates new form VistaSociosActividad
     */
    public VistaSociosActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFiltrarProcedimiento = new javax.swing.JButton();
        jButtonSalirProcedimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSociosActividad = new javax.swing.JTable();
        jComboBoxFiltrarProcedimiento = new javax.swing.JComboBox<>();

        jButtonFiltrarProcedimiento.setText("Filtrar");
        jButtonFiltrarProcedimiento.setActionCommand("FiltrarProcedimiento");

        jButtonSalirProcedimiento.setText("Salir");
        jButtonSalirProcedimiento.setActionCommand("SalirProcedimiento");

        jTableSociosActividad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSociosActividad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxFiltrarProcedimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFiltrarProcedimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalirProcedimiento)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jComboBoxFiltrarProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiltrarProcedimiento)
                    .addComponent(jButtonSalirProcedimiento))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonFiltrarProcedimiento;
    public javax.swing.JButton jButtonSalirProcedimiento;
    public javax.swing.JComboBox<String> jComboBoxFiltrarProcedimiento;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableSociosActividad;
    // End of variables declaration//GEN-END:variables
}
